
image: python:3.9

stages:
    - test

before_script:
       - pip install --upgrade pip 
       - pip install -r requirements.txt
       - apt-get update && apt-get install -y wget unzip
       - wget -qO- https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /usr/share/keyrings/google-chrome-keyring.gpg
       - apt-get update && apt-get install -y google-chrome-stable
test_app:
    stage: test
    script:
        - echo "run the automation test script"
        - behave --no-capture featurefiles/elements.feature  

