image: python:3.9  # Use Python Docker image

variables:
  CHROME_VERSION: "114.0.5735.90"
  CHROMEDRIVER_VERSION: "114.0.5735.90"
  DISPLAY: ":99"

before_script:
  - apt-get update && apt-get install -y wget unzip curl xvfb
  - echo "Installing Google Chrome..."
  - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome-stable_current_amd64.deb || apt-get install -f -y
  - google-chrome --version

  - echo "Installing ChromeDriver..."
  - wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - mv chromedriver /usr/local/bin/
  - chmod +x /usr/local/bin/chromedriver
  - chromedriver --version

  - echo "Setting up virtual display..."
  - Xvfb :99 -screen 0 1920x1080x24 &

  - echo "Installing dependencies..."
  - pip install --no-cache-dir -r requirements.txt
  - pip install behave selenium webdriver-manager

stages:
  - test

run-tests:
  stage: test
  script:
    - echo "Running Selenium Tests..."
    - behave features/Newuserlogin.feature
  artifacts:
    when: always
    paths:
      - reports/
  only:
    - master  # Run tests only on the main branch