
image: python:3.9

stages:
    - test

before_script:
    - apt-get update && apt-get install -y wget unzip
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt-get install -y ./google-chrome-stable_current_amd64.deb
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m unittest discover tests
test_app:
    stage: test
    script:
        - echo "run the automation test script"
        - behave --no-capture featurefiles/elements.feature  

