image: python:3.9

stages:
    -test
before script:
       -pip install --upgrade pip 
       -pip install -r requirements.txt
test-app:
    stage: test
    script:
        - echo "run the automation test script"
        - behave featurefiles/elements.feature  