image: python:3.9

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - apt-get update && apt-get install -y chromium-browser xvfb
  - export DISPLAY=:99
  - Xvfb :99 -screen 0 1024x768x24 &
  - sleep 2

test_app:
  stage: test
  script:
    - echo "Run the automation test script"
    - behave featurefiles/elements.feature