
image: python:3.9

stages:
    - test

before_script:
       - pip install --upgrade pip 
       - pip install -r requirements.txt
test_app:
    stage: test
    script:
        - echo "run the automation test script"
        - behave --no-capture featurefiles/elements.feature  

