# image: python:3.9

# stages:
#   - test

# before_script:
#   - pip install --upgrade pip
#   - pip install -r requirements.txt
#   - apt-get update 
#   - rm -rf ~/.cache/webdriver-manager 
#   # Important: Update package lists FIRST
#   - apt-get install -y chromium  # Install the 'chromium' package (usually works better)
#   - apt-get install -y xvfb
#   - export DISPLAY=:99
#   - Xvfb :99 -screen 0 1024x768x24 &
#   - sleep 2

# test_app:
#   stage: test
#   script:
#     - echo "Run the automation test script"
#     - behave featurefiles/elements.feature

image: python:3.9

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - apt-get update
  - apt-get install -y xvfb  # Install xvfb *before* trying to use it
  - export DISPLAY=:99
  - Xvfb :99 -screen 0 1024x768x24 &
  - sleep 2
  - wget https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chromedriver-linux64.zip 
  - unzip chromedriver-linux64.zip
  - chmod +x chromedriver
  - export PATH=$PATH:./chromedriver # Add ChromeDriver to PATH
  - google-chrome --version # Print Chrome version to logs
  - pip install --upgrade webdriver-manager

test_app:
  stage: test
  script:
    - echo "Run the automation test script"
    - behave featurefiles/elements.feature







