image: python:3.9

stages:
  - test

before_script:
  # - pip install --upgrade pip
  # - pip install -r requirements.txt
  # - apt-get update
  # - apt-get install -y xvfb  # Install xvfb *before* trying to use it
  # - export DISPLAY=:99
  # - Xvfb :99 -screen 0 1024x768x24 &
  # - sleep 2
  # - wget https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chromedriver-linux64.zip 
  # - unzip chromedriver-linux64.zip
  # - chmod +x chromedriver-linux64/chromedriver  # Correct path to chromedriver
  # - export PATH=$PATH:./chromedriver-linux64
  # - pip install --upgrade webdriver-manager
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - apt-get update
  - apt-get install -y xvfb libappindicator3-1 lsb-release wget ca-certificates libx11-6 libxext6 libxrender1 libxtst6 libcups2
  - export DISPLAY=:99
  - Xvfb :99 -screen 0 1024x768x24 &
  - sleep 2
  - pip install --upgrade webdriver-manager

test_app:
  stage: test
  script:
    - echo "Run the automation test script"
    - behave featurefiles/elements.feature







