
stages:
    test:
    - "test_job"
test-app:
    image: python:3.9
    stage: build
    before script:
       -pip install --upgrade pip 
       -pip install -r requirements.txt
    script:
        - echo "run the automation test script"
        - behave featurefiles/elements.feature  